name: Move branch contents to folder in main

on:
  push:
    branches:
      - '**'

jobs:
  sync-branch-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get branch name
        id: vars
        run: echo "branch_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Check out main branch
        run: git checkout main

      - name: Create folder and verify
        run: |
          branch_name="${{ env.branch_name }}"
          if [ ! -d "./${branch_name}" ]; then
            mkdir -p "./${branch_name}"
            echo "Directory ./${branch_name} created successfully."
          else
            echo "Directory ./${branch_name} already exists."
          fi

      - name: Move files into folder
        run: |
          branch_name="${{ env.branch_name }}"
          git checkout ${{ env.branch_name }} -- .
          for item in *; do
            if [ "$item" != "${branch_name}" ] && [ "$item" != ".git" ]; then
              mv "$item" "./${branch_name}/"
            fi
          done
          git add .

      - name: Commit changes
        run: |
          git commit -m "Move contents of branch ${{ env.branch_name }} to folder ${{ env.branch_name }} in main"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
