name: Move branch contents to folder in main

on:
  push:
    branches:
      - '**'   # Trigger on any branch push

jobs:
  sync-branch-to-main:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full history is fetched

      # Set up Git credentials
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Get the current branch name
      - name: Get branch name
        id: vars
        run: echo "branch_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      # Check out the main branch
      - name: Check out main branch
        run: git checkout main

      # Create a folder named after the branch and copy the files
      - name: Create folder and move files
        run: |
          branch_name="${{ env.branch_name }}"
          
          # Ensure the directory exists
          mkdir -p "./${branch_name}"

          # Check out the branch content, but exclude the .git folder
          git checkout ${{ env.branch_name }} -- .
          
          # Move all files except the new folder into the folder
          for item in *; do
            if [ "$item" != "${branch_name}" ] && [ "$item" != ".git" ]; then
              mv "$item" "./${branch_name}/"
            fi
          done
          
          git add .


      # Commit changes to the main branch
      - name: Commit changes
        run: |
          git commit -m "Move contents of branch ${{ env.branch_name }} to folder ${{ env.branch_name }} in main"
          git push origin main
