name: Move branch contents to folder in main

on:
  push:
    branches:
      - '**'

jobs:
  sync-branch-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get branch name
        id: vars
        run: echo "branch_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Checkout the branch where files exist
        run: git checkout ${{ env.branch_name }}

      - name: Move branch contents to main branch
        run: |
          branch_name="${{ env.branch_name }}"

          # Switch to the main branch
          git checkout main

          # Ensure the demo folder exists in main
          if [ ! -d "./${branch_name}" ]; then
            mkdir -p "./${branch_name}"
          fi

          # Checkout the files from the feature branch into the workspace
          git checkout ${{ env.branch_name }} -- .

          # Move files to the correct folder
          for item in *; do
            if [ "$item" != "${branch_name}" ] && [ "$item" != ".git" ]; then
              mv "$item" "./${branch_name}/"
            fi
          done

      - name: Commit the changes to main
        run: |
          git add .
          git commit -m "Move contents of branch ${{ env.branch_name }} to folder ${{ env.branch_name }} in main"

      - name: Push changes to main
        run: git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
